'use client';

import LeadMagnetGate from '@/components/LeadMagnetGate';

const categories = [
  { num: 1, name: 'Purchased Goods & Services', direction: 'Upstream', description: 'Emissions from cradle-to-gate production of goods and services purchased by the reporting company.', dataNeeded: 'Procurement spend data by category, supplier-specific emission factors, or industry-average LCA data', method: 'Spend-based (easiest), Average-data, Hybrid, or Supplier-specific (most accurate)' },
  { num: 2, name: 'Capital Goods', direction: 'Upstream', description: 'Emissions from cradle-to-gate production of capital goods (equipment, buildings, vehicles).', dataNeeded: 'Capital expenditure data by asset type, asset-level emission factors', method: 'Spend-based or Average-data' },
  { num: 3, name: 'Fuel- and Energy-Related Activities', direction: 'Upstream', description: 'Emissions from extraction, production, and transportation of fuels and energy not included in Scope 1 or 2.', dataNeeded: 'Energy consumption data (already tracked for Scope 1/2), well-to-tank emission factors', method: 'Average-data using well-to-tank factors' },
  { num: 4, name: 'Upstream Transportation & Distribution', direction: 'Upstream', description: 'Emissions from transporting and distributing purchased products from tier 1 suppliers to the reporting company.', dataNeeded: 'Freight data (tonne-km), mode of transport, fuel consumption of logistics providers', method: 'Distance-based, Fuel-based, or Spend-based' },
  { num: 5, name: 'Waste Generated in Operations', direction: 'Upstream', description: 'Emissions from third-party disposal and treatment of waste generated by the reporting company.', dataNeeded: 'Waste volumes by type and disposal method (landfill, recycling, incineration, composting)', method: 'Waste-type-specific method' },
  { num: 6, name: 'Business Travel', direction: 'Upstream', description: 'Emissions from employee business travel in vehicles not owned by the company (flights, rail, rental cars, hotels).', dataNeeded: 'Travel booking data, distance traveled by mode, hotel nights', method: 'Distance-based or Spend-based' },
  { num: 7, name: 'Employee Commuting', direction: 'Upstream', description: 'Emissions from employees traveling between home and worksite.', dataNeeded: 'Employee survey data on commute distance, mode, and remote work frequency', method: 'Average-data using commute surveys' },
  { num: 8, name: 'Upstream Leased Assets', direction: 'Upstream', description: 'Emissions from operation of assets leased by the reporting company (not in Scope 1/2).', dataNeeded: 'Leased asset energy consumption, asset type and usage data', method: 'Asset-specific or Average-data' },
  { num: 9, name: 'Downstream Transportation & Distribution', direction: 'Downstream', description: 'Emissions from transporting and distributing sold products to end consumers.', dataNeeded: 'Freight data for outbound logistics, distribution center energy use', method: 'Distance-based or Spend-based' },
  { num: 10, name: 'Processing of Sold Products', direction: 'Downstream', description: 'Emissions from processing of intermediate products sold by the reporting company.', dataNeeded: 'Processing energy and emissions data from downstream manufacturers', method: 'Average-data or Site-specific' },
  { num: 11, name: 'Use of Sold Products', direction: 'Downstream', description: 'Emissions from end-use of goods and services sold by the reporting company.', dataNeeded: 'Product energy consumption, lifetime usage assumptions, units sold', method: 'Product-level calculation using usage profiles' },
  { num: 12, name: 'End-of-Life Treatment of Sold Products', direction: 'Downstream', description: 'Emissions from disposal of products sold by the reporting company at end of life.', dataNeeded: 'Product material composition, expected disposal method proportions', method: 'Waste-type method using product composition' },
  { num: 13, name: 'Downstream Leased Assets', direction: 'Downstream', description: 'Emissions from operation of assets owned by the reporting company and leased to others.', dataNeeded: 'Tenant energy consumption data, building characteristics', method: 'Asset-specific or Average-data' },
  { num: 14, name: 'Franchises', direction: 'Downstream', description: 'Emissions from operation of franchises not included in Scope 1/2.', dataNeeded: 'Franchisee energy and fuel data, floor area, revenue', method: 'Franchise-specific or Average-data' },
  { num: 15, name: 'Investments', direction: 'Downstream', description: 'Emissions from operation of investments (equity, debt, project finance) in the reporting period.', dataNeeded: 'Investee Scope 1+2 emissions, ownership share, investment amounts', method: 'Investment-specific or Average-data (PCAF methodology)' },
];

export default function Scope3WorksheetClient() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16">
      <div className="mb-8 text-center">
        <div className="inline-flex items-center gap-2 rounded-full bg-teal-50 dark:bg-teal-900/30 px-4 py-1.5 text-sm font-semibold text-teal-700 dark:text-teal-400 mb-4">
          📊 Free Resource
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold font-heading text-brand-800 dark:text-white">Scope 3 Emissions Worksheet</h1>
        <p className="mt-3 text-lg text-brand-500 dark:text-gray-400 max-w-2xl mx-auto">A step-by-step worksheet covering all 15 GHG Protocol Scope 3 categories to help you measure your full value chain emissions.</p>
      </div>

      <LeadMagnetGate
        title="Access the Scope 3 Worksheet"
        description="Enter your email to unlock the complete step-by-step worksheet with data requirements and calculation methods for all 15 categories."
        source="scope-3-emissions-worksheet"
      >
        <div className="print:p-0">
          <div className="text-center mb-10 print:mb-6">
            <h1 className="text-3xl font-extrabold font-heading text-brand-800 dark:text-white">Scope 3 Emissions Measurement Worksheet</h1>
            <p className="text-brand-500 dark:text-gray-400 mt-2">By Council Fire — resources.councilfire.org</p>
            <button onClick={() => window.print()} className="mt-4 inline-flex items-center gap-2 rounded-full bg-brand-100 dark:bg-white/10 px-4 py-2 text-sm font-semibold text-brand-700 dark:text-gray-300 hover:bg-brand-200 dark:hover:bg-white/20 transition-colors print:hidden">
              🖨️ Print / Save as PDF
            </button>
          </div>

          {/* Getting Started */}
          <div className="mb-10 p-6 rounded-2xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800">
            <h2 className="font-bold text-brand-800 dark:text-white mb-2">Before You Start</h2>
            <ol className="list-decimal list-inside space-y-2 text-sm text-brand-600 dark:text-gray-300">
              <li><strong>Screen for relevance:</strong> Not all 15 categories apply to every organization. Identify which are material to your business.</li>
              <li><strong>Prioritize by magnitude:</strong> Focus on the categories that represent the largest share of your value chain emissions first.</li>
              <li><strong>Start with spend-based methods</strong> where primary data isn&apos;t available — you can improve data quality over time.</li>
              <li><strong>Document assumptions:</strong> Track all assumptions, data sources, and emission factors for audit and year-over-year comparison.</li>
            </ol>
          </div>

          {/* Categories */}
          <div className="space-y-6">
            {categories.map((cat) => (
              <div key={cat.num} className="rounded-xl border border-brand-200 dark:border-white/10 bg-white dark:bg-[#222] overflow-hidden print:break-inside-avoid">
                <div className="flex items-center gap-3 px-6 py-4 bg-brand-50 dark:bg-white/5 border-b border-brand-200 dark:border-white/10">
                  <span className="inline-flex items-center justify-center w-8 h-8 rounded-lg bg-teal-100 dark:bg-teal-900/30 text-teal-700 dark:text-teal-400 text-sm font-bold shrink-0">{cat.num}</span>
                  <div>
                    <h3 className="font-bold text-brand-800 dark:text-white text-sm">{cat.name}</h3>
                    <span className="text-xs text-brand-400 dark:text-gray-500">{cat.direction}</span>
                  </div>
                </div>
                <div className="p-6 space-y-4">
                  <p className="text-sm text-brand-600 dark:text-gray-300">{cat.description}</p>
                  <div>
                    <h4 className="text-xs font-bold text-brand-500 dark:text-gray-400 uppercase tracking-wider mb-1">Data Needed</h4>
                    <p className="text-sm text-brand-700 dark:text-gray-300">{cat.dataNeeded}</p>
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-brand-500 dark:text-gray-400 uppercase tracking-wider mb-1">Recommended Method</h4>
                    <p className="text-sm text-brand-700 dark:text-gray-300">{cat.method}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="text-xs font-semibold text-brand-500 dark:text-gray-400 block mb-1">Relevant? (Y/N)</label>
                      <input type="text" className="w-full rounded-lg border border-brand-200 dark:border-white/10 bg-brand-50 dark:bg-white/5 px-3 py-2 text-sm print:border-gray-400" />
                    </div>
                    <div>
                      <label className="text-xs font-semibold text-brand-500 dark:text-gray-400 block mb-1">Priority (H/M/L)</label>
                      <input type="text" className="w-full rounded-lg border border-brand-200 dark:border-white/10 bg-brand-50 dark:bg-white/5 px-3 py-2 text-sm print:border-gray-400" />
                    </div>
                  </div>
                  <div>
                    <label className="text-xs font-semibold text-brand-500 dark:text-gray-400 block mb-1">Notes / Data Sources</label>
                    <textarea rows={2} className="w-full rounded-lg border border-brand-200 dark:border-white/10 bg-brand-50 dark:bg-white/5 px-3 py-2 text-sm print:border-gray-400" />
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-12 p-6 rounded-2xl bg-teal-50 dark:bg-teal-900/20 border border-teal-200 dark:border-teal-800 text-center print:hidden">
            <h3 className="font-bold text-brand-800 dark:text-white">Need help measuring your Scope 3 emissions?</h3>
            <p className="text-sm text-brand-500 dark:text-gray-400 mt-1">Council Fire specializes in value chain emissions measurement and reduction strategies.</p>
            <a href="https://www.councilfire.org/contact" className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#258193] px-6 py-2.5 text-sm font-bold text-white hover:bg-[#1e6b7a] transition-colors">
              Talk to Our Team →
            </a>
          </div>
        </div>
      </LeadMagnetGate>
    </div>
  );
}
